### ISSUE TITLE
CDI 2.0 Compatibility ? 

### ISSUE THREAD

**Issue by dgautier** [astefanutti/metrics-cdi#21] opened 2018-02-28 18:53 UTC
Hello, 

I'm trying to run metrics-cdi within weld 3.0.3, but i'm currently facing this:
```
Caused by: org.jboss.weld.exceptions.IllegalStateException: WELD-000117: Required service interface org.jboss.weld.module.ExpressionLanguageSupport has not been specified for test.jar
	at org.jboss.weld.manager.BeanManagerImpl.getELResolver(BeanManagerImpl.java:1106)
	at org.jboss.weld.util.ForwardingBeanManager.getELResolver(ForwardingBeanManager.java:189)
	at io.astefanutti.metrics.cdi.MetricNameFactory.metricName(MetricNameFactory.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

If you have any tips ?

Thanks
David

**Comment by astefanutti** [comment] 2018-03-02 17:43
I've just tried adding some tests in 293d84ab8a712c8e972108ed5bc411d835340092 and d6ba0af6d5420f1b54e3a4e60158ae7a4d1cce9f.

It turns out I've been able to reproduce your issue and had to add the following dependency:

https://github.com/astefanutti/metrics-cdi/blob/e67a7ea524928832919905a14da430d65e0f90e0/envs/ee/pom.xml#L119-L124

That module registers the implementation for the required service `org.jboss.weld.module.ExpressionLanguageSupport`.

So depending on your platform, you have to have an equivalent implementation.

**Comment by astefanutti** [comment] 2018-04-10 10:15
Let me close this. Feel free to reopen if needed.

**Closed by astefanutti** 2018-04-10 10:15 UTC
